### ISSUE TITLE
Theme on picture

### ISSUE THREAD

**Issue by michalmw** [atom/ide-typescript#20]
Hello,

On readme, you paste the image of code.
Can you show name a theme?

Thanks

**Comment by damieng** [comment]
The one in the README for this repo?  It is simply One-Light UI with One-Dark syntax. 

If you mean the purple theme on the Atom IDE site.. I do not think that has been released and was something our graphic designer was experimenting with.

**Comment by michalmw** [comment]
Hey,
thanks for your answer.
What about this?
https://pasteboard.co/GK5iCWE.png <- is possible to configure this type theme?

**Comment by damieng** [comment]
That theme is not available to my knowledge - the guy who would know for sure is on vacation.

**Comment by haikyuu** [comment]
@michalmw You can tweak the atom-light-ui using a variation of
```less
.theme-one-light-ui {
  .config-menu, .flexbox-repaint-hack, .pane, .tab.sortable{
    background-color: #eae5ee;
  }
  .tab.sortable.active, .editor{
    background-color: #faf5ff;
  }
  .line-number{
    color: rgb(151, 46, 253) !important;
  }
}
```
